apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  application: |
    [
      { "path": "", "roles": ["DEV"], "method": "GET" },
      { "path": "/[0-9a-z]+", "roles": ["DEV"], "method": "GET" },
      { "path": "", "roles": ["DEV"], "method": "POST" },
      { "path": "/[0-9a-z]+", "roles": ["DEV"], "method": "PUT" },
      { "path": "/[0-9a-z]+", "roles": ["DEV"], "method": "DELETE" }
    ]
  profile: |
    [
      { "path": "", "method": "GET" },
      { "path": "/[0-9a-z]{24}", "method": "GET" },
      { "path": "", "method": "PUT" }
    ]
  auth: |
    [
      { "path": "/login", "method": "POST", "anonymous": true },
      { "path": "/register", "method": "POST", "anonymous": true },
      { "path": "/refresh", "method": "POST", "anonymous": true },
      { "path": "/user", "roles": ["TEC"], "method": "GET"},
      { "path": "/user/[0-9a-z]{24}", "roles": ["TEC"], "method": "PUT"}
    ]
  log: |
    [
      { "path": "", "method": "GET", "roles": ["TEC"] }
    ]

  restaurant: |
    [
      { "path": "", "method": "GET" },
      { "path": "/[0-9a-z]{24}", "method": "GET" },
      { "path": "", "roles": ["RES"], "method": "POST" },
      { "path": "/[0-9a-z]{24}", "roles": ["RES"], "method": "PUT" },
      { "path": "/[0-9a-z]{24}", "roles": ["RES"], "method": "DELETE" },

      { "path": "/[0-9a-z]{24}/menu", "method": "GET" },
      { "path": "/[0-9a-z]{24}/menu/[0-9a-z]{24}", "method": "GET" },
      { "path": "/[0-9a-z]{24}/menu", "roles": ["RES"], "method": "POST" },
      { "path": "/[0-9a-z]{24}/menu/[0-9a-z]{24}", "roles": ["RES"], "method": "PUT" },
      { "path": "/[0-9a-z]{24}/menu/[0-9a-z]{24}", "roles": ["RES"], "method": "DELETE" },

      { "path": "/[0-9a-z]{24}/article", "method": "GET" },
      { "path": "/[0-9a-z]{24}/article/[0-9a-z]{24}", "method": "GET" },
      { "path": "/[0-9a-z]{24}/article", "roles": ["RES"], "method": "POST" },
      { "path": "/[0-9a-z]{24}/article/[0-9a-z]{24}", "roles": ["RES"], "method": "PUT" },
      { "path": "/[0-9a-z]{24}/article/[0-9a-z]{24}", "roles": ["RES"], "method": "DELETE" },

      { "path": "/[0-9a-z]{24}/category", "method": "GET" },
      { "path": "/[0-9a-z]{24}/category/[0-9a-z]{24}", "method": "GET" },
      { "path": "/[0-9a-z]{24}/category", "roles": ["RES"], "method": "POST" },
      { "path": "/[0-9a-z]{24}/category/[0-9a-z]{24}", "roles": ["RES"], "method": "PUT" },
      { "path": "/[0-9a-z]{24}/category/[0-9a-z]{24}", "roles": ["RES"], "method": "DELETE" }
    ]
  order: |
    [
      { "path": "", "roles": ["USR", "RES"], "method": "GET" },
      { "path": "/[0-9a-z]{24}", "roles": ["USR", "RES"], "method": "GET" },
      { "path": "", "roles": ["USR"], "method": "POST" },
      { "path": "/[0-9a-z]{24}", "roles": ["RES"], "method": "PUT" },
      { "path": "/[0-9a-z]{24}", "roles": ["USR", "RES"], "method": "DELETE" }
    ]
  delivery: |
    [
      { "path": "", "roles": ["DEL"], "method": "GET" },
      { "path": "/[0-9a-z]{24}", "roles": ["USR", "DEL", "RES"], "method": "GET" },
      { "path": "/[0-9a-z]{24}", "roles": ["DEL"], "method": "PUT" }
    ]
  notification: |
    [
      { "path": "", "method": "POST" },
      { "path": "/sendNotification", "method": "POST" }
    ]
  statistic: |
    [
      { "path": "/[0-9a-z]{24}", "roles": ["RES"], "method": "GET"}
    ]
