apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mongo-root-username: M3h6cWZyYzgzSFBkRDdUaFRlTnhoQVhySEViM2lCczc=
  mongo-root-password: OHhiSDNMODdKSFFreTk4SmlyZG02RzNFTUpHOXNqa2I=