apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  application: |
    [
      { "path": "", "roles": ["DEV"], "method": "GET" },
      { "path": "", "roles": ["DEV"], "method": "POST" }
    ]
